apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-keda
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-keda
    envSourceContainerName: nginx-container
  pollingInterval:  30
  cooldownPeriod:   300
  idleReplicaCount: 1
  minReplicaCount:  2
  maxReplicaCount:  4
  # fallback:
  #   failureThreshold: 3
  #   replicas: 6
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-k8s.monitoring.svc:9090
      metricName: http_requests_total
      query: container_cpu_usage_seconds_total{pod="nginx-server-hpa-76995476fc-nlb9t"} * 100
      threshold: '10'