apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-hpa
  namespace: apps
spec:
  # type: NodePort
  selector:
    test: hpa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 31110