apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-keda
  namespace: apps
spec:
  selector:
    matchLabels:
      test: keda
  template:
    metadata:
      labels:
        test: keda
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
