apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-keda
  namespace: apps
spec:
  # type: NodePort
  selector:
    test: keda
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 31111